### ISSUE TITLE
[Bug]: wrong version of slim-sprig

### ISSUE THREAD

**Issue by hexinzhe** [megaease/easegress#1019]
**Describe the bug**
I think easegress used the wrong version of [slim-sprig](https://github.com/go-task/slim-sprig). v2.20.0 is an old version, in which the "get" API was not even available for dict. Therefore, this will affect obtaining the `data` in the pipeline.

**To Reproduce**
Just try using `get $.data.PIPELINE` in v2.4.1 or later

**Comment by localvar** [comment]
hi @hexinzhe , I checked `go.mod` and think we are using the correct version of `slim-sprig`.

could you please provide the full yaml configuration of your pipeline and the detailed error message?

**Comment by hexinzhe** [comment]
Just check https://github.com/go-task/slim-sprig/blob/v2.20.0/dict.go and https://github.com/go-task/slim-sprig/blob/master/dict.go, the `get` function in version v2.20.0 does not exist.

**Comment by hexinzhe** [comment]
@localvar 

```yaml
name: fallback
kind: Pipeline
flow:
  - filter: proxy
    jumpIf:
      serverError: errResponse
      "": END
  - filter: errResponse
filters:
  - name: proxy
    kind: Proxy
    pools:
      - servers:
          - url: {PROXY_SERVER}
#          - url: http://152.70.110.184:4002

  - name: errResponse
    kind: ResponseBuilder
    template: |
      {{ $url := "null" }}
      {{- range $k, $v := .requests.DEFAULT.Header -}}
      {{$value := index $v 0}}
      {{- if (regexMatch "^[0-9a-zA-Z].*"  $value) }}
      {{- if (eq "server-name" (lower $k)) }}
      {{ $u := get $.data.PIPELINE $value }}
      {{ $url = $u.redirect }}
      {{- end -}}
      {{- end -}}
      {{- end -}}
      {{log "info" (printf "fallback to %s%s?%s" $url .requests.DEFAULT.URL.Path .requests.DEFAULT.URL.RawQuery)}}
      
      statusCode: 302
      headers:
        Location: ["{{$url}}{{.requests.DEFAULT.URL.Path}}?{{.requests.DEFAULT.URL.RawQuery}}"]
  - name: defaultResponse
    kind: ResponseBuilder
    sourceNamespace: DEFAULT
data:
  1:
    redirect: https://1.com:30000
  2:
    redirect: https://2.com:30000
  3:
    redirect: https://3.com:30000
```

This yaml apply in easegress v2.4.0 is alright, but in v2.4.1 or later, will produce an error.

```
2023-06-21T04:40:28.403Z	ERROR	supervisor/object.go:395	fallback: recover from Init, err: template: :6: function "get" not defined, stack trace:
goroutine 223 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.9/x64/src/runtime/debug/stack.go:24 +0x65
github.com/megaease/easegress/pkg/supervisor.(*ObjectEntity).InitWithRecovery.func1()
	/home/runner/work/easegress/easegress/pkg/supervisor/object.go:396 +0x79
panic({0x2d214c0, 0xc002212b20})
	/opt/hostedtoolcache/go/1.19.9/x64/src/runtime/panic.go:884 +0x212
text/template.Must(...)
	/opt/hostedtoolcache/go/1.19.9/x64/src/text/template/helper.go:26
github.com/megaease/easegress/pkg/filters/builder.(*Builder).reload(0xc002212a38, 0xc001aa6898)
	/home/runner/work/easegress/easegress/pkg/filters/builder/builder.go:56 +0x406
github.com/megaease/easegress/pkg/filters/builder.(*ResponseBuilder).reload(...)
	/home/runner/work/easegress/easegress/pkg/filters/builder/responsebuilder.go:110
github.com/megaease/easegress/pkg/filters/builder.(*ResponseBuilder).Init(0x38393d8?)
	/home/runner/work/easegress/easegress/pkg/filters/builder/responsebuilder.go:100 +0x2f
github.com/megaease/easegress/pkg/object/pipeline.(*Pipeline).reload(0xc00213e5c0, 0x0)
	/home/runner/work/easegress/easegress/pkg/object/pipeline/pipeline.go:275 +0x36e
github.com/megaease/easegress/pkg/object/pipeline.(*Pipeline).Init(0xcc?, 0x3831560?, {0xc00213e5c0?, 0x0?})
	/home/runner/work/easegress/easegress/pkg/object/pipeline/pipeline.go:224 +0x65
github.com/megaease/easegress/pkg/supervisor.(*ObjectEntity).InitWithRecovery(0xc002138870, {0x37ff260, 0xc0017ed4a0})
	/home/runner/work/easegress/easegress/pkg/supervisor/object.go:404 +0x102
github.com/megaease/easegress/pkg/object/trafficcontroller.(*TrafficController).CreatePipeline(0xc001384b70, {0x32e7f06, 0x7}, 0xc002138870)
	/home/runner/work/easegress/easegress/pkg/object/trafficcontroller/trafficcontroller.go:435 +0x251
github.com/megaease/easegress/pkg/object/rawconfigtrafficcontroller.(*RawConfigTrafficController).handleEvent(0xc0018abb40, 0xc00205d6c8)
	/home/runner/work/easegress/easegress/pkg/object/rawconfigtrafficcontroller/rawconfigtrafficcontroller.go:156 +0x3aa
github.com/megaease/easegress/pkg/object/rawconfigtrafficcontroller.(*RawConfigTrafficController).run(0xc0018abb40)
	/home/runner/work/easegress/easegress/pkg/object/rawconfigtrafficcontroller/rawconfigtrafficcontroller.go:128 +0x2e
created by github.com/megaease/easegress/pkg/object/rawconfigtrafficcontroller.(*RawConfigTrafficController).reload
	/home/runner/work/easegress/easegress/pkg/object/rawconfigtrafficcontroller/rawconfigtrafficcontroller.go:119 +0x1db
```
