### ISSUE TITLE
TCP proxy supporting

### ISSUE THREAD

**Issue by benja-wu** [megaease/easegress#229]
## Background
* Easegress works as an L7-level proxy with multiple useful features. But it can't work as an L4-level proxy. 

## Requirement
* Make Easegress as an L4-level proxy as well

### Question1: Which kind of instance should this feature belong to?
* Currently, Easegress has a big catalog as `TafficGate` for specified application protocols, such as `HTTP`, `MQTT`, and `WebSocket`.
*  There is a system-level controller called `TrafficController`, which manages HTTP-protocol-based `HTTPServer` and `Pipeline` by namespace. 

> Propose to add a new `TCPProxy` as `HTTPServer`. Other application level protocol implementations which are using TCP connection directly can be benefited from this `TCPServer` managed by `TrafficController` 

### Question2: Are there some awesome, open-sourced package can we directly import？
* The goproxy[1] seems to be a quite popular proxy implemented in Golang.
* 

### Question 3: How many basic features should a TCP proxy supported?
* TLS supporting: multiple certificates supporting?
* Multiple backends load-balancing: Round Robin, Weight Round Robin, Random...?
* Timeout: sending timeout, connection timeout, receiving timeout? 
* Limited connection？ Reusing `NewLimitListener` in `Easegress`'s util pkg? 

> Propose confirming the `TCPProxy ` spec firstly. In this spec, it should have a `load balance` type, listening port, backend array, TLS certificate encoding in base64, and so on...

### Question 4: Should we introduce these advanced features in the future?
* Health checking: such as NGINX[3] 
* Failover: such as Google Cloud balancing[4]
.....

## Summary
* This is a draft design for the opening discussion. **It's welcome to join us for telling your requirements and user scenarios, and let's figure out the basic, core features this feature should have together.** Since Easegress is focusing on modern traffic orchestrating, some nice-to-have advanced feature we can hold it on and plan it implemented in the future. 
* Once we come to a `Version 1` conclusion for this `TCPProxy`, **PR for this implementation is also welcomed!** 

## Reference
1. https://github.com/snail007/goproxy
2. https://doc.traefik.io/traefik/routing/services/
3. https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-health-check/
4. https://cloud.google.com/load-balancing/docs/tcp

**Comment by benja-wu** [comment]
@jxd134 @siaron 
Maybe we can figure out the design together. :-)

**Comment by jxd134** [comment]
(1) we should seperate tcp/udp proxy with httpserver.
(2) we can use http balance method for tcp/udp proxy (expect headerhash);
(3) there is no need to add tcp/udp pipeline like httppipeline right now;
(4) which indicators of tcp/udp are counted? eg: `connection num`/`send/recv bytes`/`packet num`;
(5)health check is invalid for tpc/udp proxy.

**Comment by siaron** [comment]
`Question 3:`  These are very useful function support.
What easegress has some introductory materials for developers. I just started go language .thanks

**Comment by benja-wu** [comment]
> `Question 3:` These are very useful function support.
> What easegress has some introductory materials for developers. I just started go language .thanks

Yes, [here](https://github.com/megaease/easegress/blob/main/doc/developer-guide.md) is an Easegress development guide.

**Comment by nevill** [comment]
We have to discuss the spec first. Let me think of an example for this feature.
```yaml
kind: TCPServer
name: server-demo
port: 10080
rules:
  - paths:
    - pathPrefix: /tcp
      backend: tcp-demo

---

name: tcp-demo
kind: TCPPipeline
flow:
  - filter: proxy
filters:
  - name: proxy
    kind: TCPProxy
    mainPool:
      servers:
      - url: tcp://127.0.0.1:9095
      - url: tcp://127.0.0.1:9096
      - url: tcp://127.0.0.1:9097
```

Or, even we can have TCP servers behind HTTPServer, like

```yaml
kind: HTTPServer
name: server-demo
port: 10080
keepAlive: true
https: false
rules:
  - paths:
    - pathPrefix: /pipeline
      backend: tcp-demo

---

name: tcp-demo
kind: TCPPipeline
flow:
  - filter: proxy
filters:
  - name: proxy
    kind: TCPProxy
    mainPool:
      servers:
      - url: tcp://127.0.0.1:9095
      - url: tcp://127.0.0.1:9096
      - url: tcp://127.0.0.1:9097
```
```
