### ISSUE TITLE
[proposal] Cluster operation

### ISSUE THREAD

**Issue by benja-wu** [megaease/easegress#233]
## Background
* Easegress embeds Etcd[1] inside. It uses Raft[2] for distributing consistency. 
* Easegress has its own cluster-start-up routine, which is quite different from original Etcd's.

### Concepts
1. Writer: Same as the Etcd's Leader/Candidate/Follower. 
2. Reader: The Etcd client, for scaling reading purposes.

### How Easegress form a cluster
1. Prepare an odd number of writer instances, pick one as the chosen `Leader`.
2. Valuing the `cluster-join-urls` in configuration by starting with the chosen `Leader`'s address first.
3. Starting the chosen `Leader` firstly.
4. Starting other `writers` one by one. (the sequence doesn't matter)
5. The known cluster member will be stored into local `member.yaml`, for saving communication cost at next time restarting.

### Dive in
* In the original Etcd start-up routine, there is an election behavior, which means not so-called chosen `Leader` is needed.
* The current Easegress cluster behavior is called a `Join` instead of an `Election`. It can save the initial competing cost. But during the daily operation, the failover election can still be processed automatically.

### Pros/Cons
Pros:  Saving initial election costing by directly join the `exist` cluster instead. 
Cons: Startup sequence required, local member YAML file removed needed at some situation. 

## Questions & Discussion  
1. Should we keep this cluster design going or just roll back to use Etcd's cluster behavior?
2. Are there any more efficient cluster start-up routines can we align with, but **still has Etcd inside**? (zookeepers? consul? ...)
3. Feel free to tell us your concerns and prefers, thx

> Please focus on cluster start-up routine discussion, Etcd inside is still Easegress' first choice. 

## References
1. https://etcd.io
2. https://en.wikipedia.org/wiki/Raft_(algorithm)

**Comment by xxx7xxxx** [comment]
There are more Pros/Cons in the current and native-etcd cluster operation:

Pros of the current cluster:

- It saves one step(`etcdctl member add`) to add members manually

Cons of the current cluster:

- The member file will easily confuse operators in the long-run maintaining including adding, restarting, pruning.
- The member adding behavior doesn't fit in k8s statefulsets startup, and causes some weird failure.

Pros of the native-etcd cluster:

- Most operation problems and solutions can be found in the huge etcd/k8s community.
- It is clearer for every newcomer only if they know etcd.

Cons of the native-etcd cluster:

- Need to add members manually (I don't even consider it as a shortcoming because scaling writers needs to be very careful)
- It seems that scale cluster size is not smooth in kubernetes either[1]

Proposal: I think etcd-native way could be a less-pain way even it has pain in scaling writers(etcd) in kubernetes. We just export all etcd startup arguments for writer role, so the operation on them is the same with mature etcd. And it seems we have to wrap some member operations in `egctl`.

[1] https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

**Comment by samutamm** [comment]
Is scaling up and down Easegress cluster an important feature to have? Does adding more Easegress writers increase cluster performance or capability? [Kubernetes does not recommend](https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#scaling-up-etcd-clusters) scaling up or down etcd cluster, but they recommend always have a static 5-member cluster.

If scaling is not an important feature, the current cluster design has less drawbacks. But I do agree that aligning the design with etcd/k8s might be beneficial for newcomers.

**Comment by samutamm** [comment]
Here’s a proposal for an alternative etch-native design for configuring the cluster. The main difference is in the start-up routine, that was discussed earlier.

## Requirements 
Cluster start-up routine should
- be closer to the way etcd is started [1](https://etcd.io/docs/v3.5/op-guide/clustering/)
- not persist `members.yaml` file that causes issues in deployment and failures

## Design
Let’s review an example of the current configuration for three node cluster:
```yaml
name: writer-n
cluster-name: cluster-test
cluster-role: writer
cluster-listen-client-urls:
 - http://0.0.0.0:2379
cluster-listen-peer-urls:
- http://0.0.0.0:2380
cluster-advertise-client-urls:
 - http://CURRENT_HOST:2379 # CURRENT_HOST equals either HOST1, HOST2 or HOST3
cluster-initial-advertise-peer-urls:
 - http://CURRENT_HOST:2380
cluster-join-urls:
 - http://HOST1:2380
 - http://HOST2:2380
 - http://HOST3:2380
api-addr: 0.0.0.0:2831
data-dir: ./data
wal-dir: ""
cpu-profile-file:
memory-profile-file:
log-dir: ./log
member-dir: ./member
debug: false
```
Currently the first URL in `cluster-join-urls` becomes the first leader and the leader changes according the etcd consensus protocol after that. Also `member-dir` defines, where info about members and  known members is persisted.

Now here's the proposal:
- add new field `cluster-writer-urls` that shall store the same content as `cluster-join-urls`, for example
```yaml
cluster-writer-urls:
 - http://HOST1:2380
 - http://HOST2:2380
 - http://HOST3:2380
```
If this new field `cluster-writer-urls` is provided, let's verify runtime that `cluster-join-urls` and `member-dir` are not present. Otherwise, user is invited to use only one of the mechanism.

I think that this proposed design would be straightforward to implement: for the proposed`cluster-writer-urls`-mode, just don't store or load `members.yaml`.

# To-do

What is the impact of this cluster-writer-urls for `etcl member purge` command? Also capability of adding or removing writers (others than the ones in fixed list of cluster-writer-urls) is yet to be defined.

**Comment by samutamm** [comment]
I will draft here design for adding and removing new members. 

## Requirements
There are four cases for member lifecycle management.
|action | role: reader | role: writer |
|---|---|---|
|add|1|3|
|remove|2|4|

The actions can consist combination of server (`easegress-server`) and admin tool (`egctl`) calls.

## Design
### Reader
#### Case 1: add reader
Adding new reader is possible after https://github.com/megaease/easegress/pull/382. Basically new reader can be added using the same easegress-server config than the initial cluster installation, appended by new name, address in `cluster.initial-cluster` and `cluster.state-flag: "exiting"`. For example, if the initial configuration has:

```yaml
name: writer-1
cluster-name: cluster-test
cluster-role: writer
...
cluster:
  listen-peer-urls:
   - http://$HOST1:2380
   ...
  initial-cluster:
   - writer-1: http://$HOST1:2380
```
Then a new reader can be added to existing cluster using following configuration for `easegress-server`:
```yaml
name: reader-1
cluster-name: cluster-test
cluster-role: reader
...
cluster:
  listen-peer-urls:
   - http://$HOST2:2380
   ...
  initial-cluster:
   - writer-1: http://$HOST1:2380
   - reader-1: http://$HOST2:2380
 state-flag: "existing"
```

#### Case 2: remove reader
Removing reader should happen by first closing the instance and then running `egctl --server HOST:PORT member remove NAME`

### Writer
#### Case 3: add writer
First register new member to existing cluster with `egctl --server HOST1,HOST2 member add NEW_NAME --peer-urls=NEW_HOST`. Then start server `easegress-server ...` in same way than when adding reader nodes (case 1).

#### Case 4: remove writer
Removing member should be the same procedure for both writer and reader (case 2).
