### ISSUE TITLE
Kubernetes Ingress Controller

### ISSUE THREAD

**Issue by localvar** [megaease/easegress#25]
## Background

We have developed an ingress controller in EaseMesh, but it is an EaseMesh-dedicated implementation. So we decide to implement a general Kubernetes ingress controller.

## Proposal

The ingress controller consumes Kubernetes Ingress Resources and converts them to an EaseGress configuration which allows the EaseGress to forward and load-balance traffic to Kubernetes pods.

## Design

1. Create a new ingress class

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: easegress
spec:
  controller: megaease.com/ingress-controller
```

2. IngressController: An controller in Easegress, also an ingress controller for Kubernetes. It creates a HTTP server for ingress traffic and watches Kubernetes Ingress, Service, Endpoint, Security to translate Kubernetes Ingress rules to Easegress pipelines dynamically.

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  ingressClassName: easegress
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: test
          servicePort: 8000
```

the ingress above will be translated to one HTTPServer and one HTTPPipeline

```yaml
kind: HTTPServer
name: http-server-ingress
port: 10080 # Indicated in the installation 
keepAlive: true
keepAliveTimeout: 75s
maxConnection: 10240
rules:
  - host: test.example.com
    paths:
    - path: /
       backend: test
```

```yaml
name: test
kind: HTTPPipeline

flow:
  - filter: proxy
filters:
  - name: proxy
    kind: Proxy
    mainPool:
      servers: # retrieved from k8s
      - url: http://10.0.1.1:19095
      - url: http://10.0.1.2:19095
      loadBalance:
        policy: roundRobin
```
