### ISSUE TITLE
[question]Is there a global filter ？

### ISSUE THREAD

**Issue by brzyangg** [megaease/easegress#253]
Our company wants to customize and develop a filter. 
For business reasons, it is found that all pipelines must use this filter.
So I want to ask if there are plans to support this global filter or how to implement this global filter is the best way.

**Comment by zhao-kun** [comment]
Many gateway products support the global filters [1], so I think this is a *REAL* requirement. We should consider how to design it carefully 

[1]https://cloud.spring.io/spring-cloud-gateway/multi/multi__global_filters.html

**Comment by benja-wu** [comment]
Hi, @brzyangg , 
I am wondering about the user cases and what this feature should support here. 
* What will u do with this global filter?
* Do u have multiple global filters requirements? If yes, which sequence should these global filters run? 
* Will u develop the logic inside this global filter by yourself?

**Comment by brzyangg** [comment]
Hi, @benja-wu 
I will answer your questions in turn. We are now investigating and developing easegress to replace the old gateway.
* I want to add authentication to all pipeline and add header by request. These are what we actually use.
* I have multiple filter needs. Our old gateway global filter is in order.
* I will develop the logic of this global filter myself.

**Comment by benja-wu** [comment]
@brzyangg I got it
Here is a quick, draft design 

## Background
* For saving operation costs, Easegress can support some kind of `global` filter, which will be executed for every HTTP routing before the actual pipeline. 

## Requirements
1. Supporting multiple `global` filters, and allow to adjust their order on the fly. 
2. These `global` filters can be executed `before` or `after` the actual routing pipeline. 
3. These `global` filters can be enabled together, once enabled, the Easegress cluster will apply them `before` or `after` to all HTTP traffic routing. 

## Design
1. Adding two embedded `global` pipelines into the Easegress system, better to wrapper them with a `System Controller`. Let's call it `GlobalHTTPFilters` right now, one Easegress cluster can only have one or zero `GlobalHTTPFilters`. 
2. These two `global` pipelines can be enabled separately.
3. Users can develop their customized logic into a filter, can when one self-develop filter's instance is configurated into `GlobalHTTPFilters`, it becomes `global` automatically.
4. HTTPServer should call this `GlobalHTTPFilters` before and after the real pipeline's handling.


5. Spec
``` yaml
name: globalFilters
kind: GlobalHTTPFilters
beforePipeline:
     // a pipeline's spec, can ignore the name, kind fields...
afterPipeline:
    // a pipeline's spec, can ignore the name, kind fields...
```

## To-Do
1. Should compare with spring-cloud-gateway and other supporting `global` filters products.

Any suggestions for this feature design are welcomed. :-)

**Comment by brzyangg** [comment]
I found that SystemController is only initialized internally.
If you define a SystemController, how to update and dynamically yaml to manage the configuration of beforePipeline and afterPipeline

**Comment by benja-wu** [comment]
@brzyangg , I think we support updating a `SystemController` with its YAML, u can check it out with [ServiceRegistry](https://github.com/megaease/easegress/blob/main/pkg/object/serviceregistry/serviceregistry.go#L30)

**Comment by brzyangg** [comment]
@benja-wu , I think `ServiceRegistry` is a `SystemController`. 
I look [the TODO](https://github.com/megaease/easegress/blob/main/pkg/object/serviceregistry/serviceregistry.go#L76) and [the Note](https://github.com/megaease/easegress/blob/main/pkg/supervisor/supervisor.go#L94)
I understand its `Spec` does not support updating.
But I am initializing a `GlobalHTTPFilters`, i need to create in and update the Spec at the same time.

The following is my understanding during the implementation `GlobalHTTPFilters`.
I don’t know if I have a problem with the implementation of `GlobalHTTPFilters`.
I defined `Spec` like this.
```go
Spec struct {
	BeforePipeline httppipeline.Spec `yaml:"beforePipeline" jsonschema:"omitempty"`
	AfterPipeline  httppipeline.Spec `yaml:"afterPipeline" jsonschema:"omitempty"`
}
```
Then after I started easegress, I found that my `object update` would not apply my configuration

**Comment by benja-wu** [comment]
> @benja-wu , I think `ServiceRegistry` is a `SystemController`. I look [the TODO](https://github.com/megaease/easegress/blob/main/pkg/object/serviceregistry/serviceregistry.go#L76) and [the Note](https://github.com/megaease/easegress/blob/main/pkg/supervisor/supervisor.go#L94) I understand its `Spec` does not support updating. But I am initializing a `GlobalHTTPFilters`, i need to create in and update the Spec at the same time.
> 
> The following is my understanding during the implementation `GlobalHTTPFilters`. I don’t know if I have a problem with the implementation of `GlobalHTTPFilters`. I defined `Spec` like this.
> 
> ```go
> Spec struct {
> 	BeforePipeline httppipeline.Spec `yaml:"beforePipeline" jsonschema:"omitempty"`
> 	AfterPipeline  httppipeline.Spec `yaml:"afterPipeline" jsonschema:"omitempty"`
> }
> ```
> 
> Then after I started easegress, I found that my `object update` would not apply my configuration

Yes, u are right, I forgot this limitation here. I think u can simply change this `SystemController` to `BusinessController` for working around. And we will fix it in the future.

**Comment by localvar** [comment]
@brzyangg , if possible, could you please create a draft PR for your work to share related code changes? this could make the discussion more smooth.

**Comment by brzyangg** [comment]
> @brzyangg , if possible, could you please create a draft PR for your work to share related code changes? this could make the discussion more smooth.

Okay, I will submit a PR to discuss this issue after finishing the code

**Comment by brzyangg** [comment]
> > @benja-wu , I think `ServiceRegistry` is a `SystemController`. I look [the TODO](https://github.com/megaease/easegress/blob/main/pkg/object/serviceregistry/serviceregistry.go#L76) and [the Note](https://github.com/megaease/easegress/blob/main/pkg/supervisor/supervisor.go#L94) I understand its `Spec` does not support updating. But I am initializing a `GlobalHTTPFilters`, i need to create in and update the Spec at the same time.
> > The following is my understanding during the implementation `GlobalHTTPFilters`. I don’t know if I have a problem with the implementation of `GlobalHTTPFilters`. I defined `Spec` like this.
> > ```go
> > Spec struct {
> > 	BeforePipeline httppipeline.Spec `yaml:"beforePipeline" jsonschema:"omitempty"`
> > 	AfterPipeline  httppipeline.Spec `yaml:"afterPipeline" jsonschema:"omitempty"`
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then after I started easegress, I found that my `object update` would not apply my configuration
> 
> Yes, u are right, I forgot this limitation here. I think u can simply change this `SystemController` to `BusinessController` for working around. And we will fix it in the future.

@benja-wu Thank you for your answer, I will try to use BusinessController to complete this function

**Comment by suchen-sci** [comment]
Hi, I am really interested in this issue and here is my design. Is this design ok?

## Design 
Object `GlobalFilters` can create several filters that can be used globally. 

Spec:
```
name: globalFilters
kind: GlobalFilters
filters:
  - name: globalValidator
    kind: Validator
    headers:
      Content-Type:
        values:
        - application/json
  - name: globalRequestAdaptor
    kind: RequestAdaptor
    header:
      set:
        X-Adapt-Key: goodplan
  - name: globalProxy
    kind: Proxy
    mainPool:
      servers:
      - url: http://127.0.0.1:9095
      - url: http://127.0.0.1:9096
      - url: http://127.0.0.1:9097
      loadBalance:
        policy: roundRobin
```
Then, we create three global filters, named: `globalValidator`, `globalRequestAdaptor`, `globalProxy`. Then we can use them in pipelines. 

In pipeline:
Spec: 
```
name: pipeline-demo
kind: HTTPPipeline
flow:
  - filter: validator
  - filter: requestAdaptor
  - filter: proxy
filters:
  - name: validator
    kind: GlobalFilterWrapper
    globalFilter: globalValidator
  - name: requestAdaptor
    kind: GlobalFilterWrapper
    globalFilter: globalRequestAdaptor
  - name: proxy
    kind: GlobalFilterWrapper
    globalFilter: globalProxy
```
`GlobalFilterWrapper` behaves just like normal filters, so it can be put in front, end or middle of a pipeline.

**Comment by localvar** [comment]
@suchen-sci , I noticed in your example, there's a `Validator` in the `GlobalFilters`, because the validation result could be success or fail, the design needs to include the `JumpIf` feature, but it seems not easy to do, because the `GlobalFilters` don't have the information of the whole pipeline.

The 2nd question is: for a `GlobalFilters` definition, will each pipeline have its own GlobalFilter instance, or will all pipelines share a single GlobalFilter instance? The former will be easy to implement, but the latter is useful in some cases, for example, I want to count the requests of all pipelines. However, if we choose to share a single instance, we will need to track information about which pipeline the request is for, and it will also make the `JumpIf` more difficult.

And another question is: the `TrafficGate` support namespaces, will a `GlobalFilters` definition be applied to all namespaces?

**Comment by suchen-sci** [comment]
@localvar Thanks a lot for your question.
1. Great question! JumpIf issue, all filter handlers return empty string when success, return non-empty string when failed. So in `GlobalFilterWrapper` we can support two kind of result, success (empty) and failed (non-empty), which can be used for JumpIf in pipeline. Or we can support result mapping. 
```
name: pipeline-demo
kind: HTTPPipeline
flow:
  - filter: validator
    jumpIf: {fail: END}
  - filter: requestAdaptor
  - filter: proxy
filters:
  - name: validator
    kind: GlobalFilterWrapper
    globalFilter: globalValidator
    resultMap:
      invalid: fail
```
2. I think we should implement a global filter for all pipelines, create one `GlobalFilters` and works for all pipeline. Emmmm, for the pipeline filter JumpIf problem, result map in `GlobalFilterWrapper` may help. 
3. Emmmm, for this problem, I plan `GlobalFilters` to be defined in all namespaces. I plan to make this `GlobalFilters` to be a `BusinessController`. Make it a `TrafficController` may make this problem unnecessarily complicated. 
@localvar Thanks a lot for your questions! They are really valuable questions!

**Comment by brzyangg** [comment]
@suchen-sci Thank you for your attention to this issue.
I noticed that in your example, the definition of `HTTPPipeline` uses `GlobalFilters`, so since all my `HTTPPipeline` needs this filter, I still need to reference this filter for each
So I have a suggestion, put the reference of `GlobalFilters` into `HTTPServer`, as follows.
```yaml

kind: HTTPServer
name: server-demo
port: 10081
globalFilters: globalFilters
keepAlive: true
https: false
rules:
    - hostRegexp: hello.com
      paths:
      -
        pathRegexp: /demo/(.*)
        backend: demo-pipeline

```
`BeforePipeline` and `AfterPipeline` are added to the definition of `GlobalFilters` to process requests and responses.

```yaml
name: globalFilters
kind: GlobalFilters
beforePipeline:
  // a pipeline's spec, can ignore the name, kind fields...
  flow:
    - filter: validator
      jumpIf: { invalid: END }
  filters:
    - name: validator
    kind: Validator
    headers:
    Content-Type:
      values:
      - application/json
      regexp: ""
    User-Agent:
      values: []
      regexp: .+
      X-Filter:
        values:
        - ""
        - mirror
        - candidate
        - hacking
        regexp: ""
afterPipeline:
    // a pipeline's spec, can ignore the name, kind fields...
```
