### ISSUE TITLE
Add more information for distributed tracing

### ISSUE THREAD

**Issue by xxx7xxxx** [megaease/easegress#316]
## Background

The tracing information only contains http server and pipeline name as different span. It's hard to debug when it comes to more details.

## Proposal

1. Add some standard information such as `path`, `method` to tags payload.
2. Support config to add user-defined tags, e.g:

```yaml
kind: HTTPServer
name: http-server-example
port: 10080
tracing:
  serviceName: httpServerExmple
  zipkin:
    hostport: 0.0.0.0:10080
    serverURL: http://localhost:9412/api/v2/spans
    sampleRate: 1
    sameSpan: true
    id128Bit: false
    tags:               # +
      MyTagKey: X-Value # +
rules:
  - paths:
    - pathPrefix: /pipeline
      backend: http-pipeline-example
```

**Comment by samutamm** [comment]
This is a good idea. I agree that `http.path` and `http.method` are good standard tags to include by default and the rest can be supported by user defined tags. Opentracing-go [span.SetTag](https://github.com/opentracing/opentracing-go/blob/e2cb74943cd81f680d00b6be69fc4a2557525727/ext/tags.go#L5-L11) can be used to add the tags.

**Comment by samutamm** [comment]
I would move the custom tags to same level as `zipkin` entry, as they are not necessary zipkin specific. Like this:

```yaml
kind: HTTPServer
name: http-server-example
port: 10080
tracing:
  serviceName: httpServerExample
  tags:                 # +
      MyTagKey: X-Value # +
  zipkin:
    hostport: 0.0.0.0:10080
    serverURL: http://localhost:9412/api/v2/spans
    sampleRate: 1
    sameSpan: true
    id128Bit: false
rules:
  - paths:
    - pathPrefix: /pipeline
      backend: http-pipeline-example
```
