### ISSUE TITLE
response body corrupt after pass ResponseAdapter

### ISSUE THREAD

**Issue by localvar** [megaease/easegress#325]
**Describe the bug**
response body corrupt after pass ResponseAdapter.

**To Reproduce**
1. create a pipeline as below
```yaml
name: index-pipeline
kind: HTTPPipeline
flow:
  - filter: proxy
  - filter: rsp
filters:
  - name: proxy
    kind: Proxy
    mainPool:
      servers:
      - url: http://172.20.2.164:9095
      loadBalance:
        policy: roundRobin
  - name: rsp
    kind: ResponseAdaptor
    header:
      del:
      set:
      add:
        AddByRequestor: "[[filter.proxy.rsp.body.name]]"
```
2. Send a request to easegress to get a response whose body size > 10k
3. See error

This issue also exists in RequestAdapter.
