### ISSUE TITLE
Failed to create pipeline when filters are not sorted as `flow`

### ISSUE THREAD

**Issue by localvar** [megaease/easegress#326]
**Describe the bug**

**To Reproduce**
1. pipeline configuration (save as `pipeline.yaml`)
```yaml
name: index-pipeline
kind: HTTPPipeline
flow:
  - filter: proxy
  - filter: rsp
filters:
  - name: rsp
    kind: ResponseAdaptor
    header:
      del:
      set:
      add:
        AddByRequestor: "[[filter.proxy.rsp.body.name]]"
  - name: proxy
    kind: Proxy
    mainPool:
      servers:
      - url: http://172.20.2.164:9095
      loadBalance:
        policy: roundRobin
```

2. Start Easegress with the command:
```bash
./easegress-server --initial-object-config-files pipeline.yaml
```
3. See error
4. But the pipeline create successfully created with below configuration:
```yaml
name: index-pipeline
kind: HTTPPipeline
flow:
  - filter: proxy
  - filter: rsp
filters:
  - name: proxy
    kind: Proxy
    mainPool:
      servers:
      - url: http://172.20.2.164:9095
      loadBalance:
        policy: roundRobin
  - name: rsp
    kind: ResponseAdaptor
    header:
      del:
      set:
      add:
        AddByRequestor: "[[filter.proxy.rsp.body.name]]"
```
