### ISSUE TITLE
GlobalFilter support

### ISSUE THREAD

**Issue by suchen-sci** [megaease/easegress#359]
## Background
As discussed in issue https://github.com/megaease/easegress/issues/253, global filters that can be used by all pipelines is a real and important requirement.

## Design 
Object `GlobalFilters` can create several filters that can be used globally. 

Spec:
```
name: globalFilters
kind: GlobalFilters
filters:
  - name: globalValidator
    kind: Validator
    headers:
      Content-Type:
        values:
        - application/json
  - name: globalRequestAdaptor
    kind: RequestAdaptor
    header:
      set:
        X-Adapt-Key: goodplan
  - name: globalProxy
    kind: Proxy
    mainPool:
      servers:
      - url: http://127.0.0.1:9095
      - url: http://127.0.0.1:9096
      - url: http://127.0.0.1:9097
      loadBalance:
        policy: roundRobin
```
Then, we create three global filters, named: `globalValidator`, `globalRequestAdaptor`, `globalProxy`. Then we can use them in pipelines. 

In pipeline:
Spec: 
```
name: pipeline-demo
kind: HTTPPipeline
flow:
  - filter: validator
  - filter: requestAdaptor
  - filter: proxy
filters:
  - name: validator
    kind: GlobalFilterWrapper
    globalFilter: globalValidator
  - name: requestAdaptor
    kind: GlobalFilterWrapper
    globalFilter: globalRequestAdaptor
  - name: proxy
    kind: GlobalFilterWrapper
    globalFilter: globalProxy
```
`GlobalFilterWrapper` behaves just like normal filters, so it can be put in front, end or middle of a pipeline.
