### ISSUE TITLE
[feature] Prometheus metrics

### ISSUE THREAD

**Issue by brzyangg** [megaease/easegress#390]
**Is your feature request related to a problem? Please describe.**
I want to pull some data through Prometheus. 
But I found that easegress did not expose the data in Prometheus model.

**Describe the solution you'd like**
I think we can add a path to `APIServer`. 
eg: `/metrics`

**Comment by brzyangg** [comment]
I have some problems while developing.I want to count the QPS and request time of each `HTTPServer`, `HTTPPipeline`. Implement wants to build on the existing `HTTPStat`. Prometheus has a [label](https://prometheus.io/docs/practices/naming/#labels).

I need a different name to set the label. But now `HTTPStat` does not have this parameter. And now it’s not easy to get the `name` when doing the stat.
 eg: [this code](https://github.com/megaease/easegress/blob/main/pkg/filter/proxy/pool.go#L261). The `HTTPPipeline` name is not get here. 

I hope to get some suggestions from you to implement this metrics.

**Comment by brzyangg** [comment]
Yes, have some problems when passing in the `name` parameter. 
Because now some `HTTPStat` belongs to a pool. When creating a `pool`, you cannot get the `HTTPPipeline` name directly, and how to distinguish while multiple pools in a `HTTPPipeline`.
So I want you to help  see how to better achieve statistical traffic(`HTTPServer` or `HTTPPipeline`) metrics.

**Comment by localvar** [comment]
Thanks, we will check that and get back to you.

**Comment by samutamm** [comment]
Proxy has access to the name of the pipeline and it's own name: 
```go
pipelineName := b.filterSpec.Pipeline()
proxyName := b.filterSpec.Name()
```
. In order to pass the names to each pool, [`proxy.newPool`](https://github.com/megaease/easegress/blob/main/pkg/filter/proxy/pool.go#L99-L123) could take them as a parameter and pass it to `HTTPStat` that is created there. To distinguish different pools, we could concatenate `pipelineName + "|" +  proxyName + "|" + tagPrefix`. (tagPrefix is provided [here](https://github.com/megaease/easegress/blob/main/pkg/filter/proxy/proxy.go#L218) and it's different for each pool of one proxy) Then in following example: 
```yaml
name: http-pipeline-1
kind: HTTPPipeline
flow:
  - filter: proxy
filters:
  - name: proxy-a
    kind: Proxy
    mainPool:
      servers:
      - url: http://127.0.0.1:9095
      loadBalance:
        policy: roundRobin
    candidatePools:
      servers:
      - url: http://127.0.0.1:9094
      loadBalance:
        policy: roundRobin
```
we'll have two names for HTTPStat:
- http-pipeline-1|proxy-a|proxy#main
- http-pipeline-1|proxy-a|proxy#candidate#0

And of course then we should add a name to HTTPStat struct. @suchen-sci What do you think about this design? @brzyangg Would this help you to fill the Prometheus label?
