### ISSUE TITLE
Support HTTP basic authentication to restrict access

### ISSUE THREAD

**Issue by zhao-kun** [megaease/easegress#404]
**Is your feature request related to a problem? Please describe.**
Using HTTP basic authentication to restrict access is a common scenario in the usage of HTTP reverse-proxy .

**Describe the solution you'd like**
I can use the `HTTP basic authentication plugin` to protect the API of the backend, avoiding the none authenticated access.

**Describe alternatives you've considered**
No any alternatives in the Easegress

**Additional context**
[The solution of the Nginx](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)

**Comment by samutamm** [comment]
I'm interested in implementing this. Here's proposal: 

We could create new filter for HTTP basic authentication:
```yaml
name: basic_auth
kind: HTTPBasicAuthentication
userFile: '/etc/apache2/.htpasswd'
# OR
useEtcd: true
```
Authorized users can be either listed in a file where each line is like `userY:_md5_encrypted_pw_` or queried from etcd dynamically for each query. 

Then this filter is used together with `GlobalFilter` and `HTTPServer`:

```yaml
name: basicAuthFilter
kind: GlobalFilter
beforePipeline:
  flow:
    - filter: basicAuth
      jumpIf: { invalid: END }
  filters:
    - name: basic_auth
      kind: HTTPBasicAuthentication
      userFile: '/etc/apache2/.htpasswd'
      # OR
      useEtcd: true
---
kind: HTTPServer
name: server
port: 10081
globalFilter: basicAuthFilter
keepAlive: true
https: true
rules:
    - paths:
      - pathPrefix: /authorized-api
        backend: authorized-api # only authorized request pass here
```

In order to access authorized paths, HTTP request should contain `Authorization` header: `Authorization: Basic <credentials>` where `<credentials>` is Base64 encoding of `userY:_md5_encrypted_pw_` user and password pair. `HTTPBasicAuthentication` filter Base64 decodes the header (only `<credentials>` part) and verifies if given user is listed in authorized users and if the MD5 encrypted password is correct. If not `HTTPBasicAuthentication` returns invalid and `GlobalFilter` will interrupt the request.

Here's sequence diagram of authorized request:
<img src="https://user-images.githubusercontent.com/7460037/148019963-6b596a6a-b84f-41b5-b2ae-6ef7b0404936.png" width="500" />
(AuthorizedUsers is either file `userFile` or etcd. AuthorizedApi is defined in `HTTPServer.rules` and here just for example)

Reference: https://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by samutamm** [comment]
Another idea:
Instead of creating new type of filter, the `httpBasic` could be part of the existing [`Validator`](https://github.com/megaease/easegress/blob/main/doc/cookbook/security.md#security-verify-credential). So `httpBasic` would the fifth option along `headers`, `jwt`, `signer` and `oauth2` that we have currently. Here's the previous example updated:

```yaml
name: basicAuthFilter
kind: GlobalFilter
beforePipeline:
  flow:
    - filter: basicAuth
      jumpIf: { invalid: END }
  filters:
    - name: basicAuth
      kind: Validator
      basicAuth:
        userFile: '/etc/apache2/.htpasswd'
        # OR
        useEtcd: true
---
kind: HTTPServer
name: server
port: 10081
globalFilter: basicAuthFilter
keepAlive: true
https: true
rules:
    - paths:
      - pathPrefix: /authorized-api
        backend: authorized-api # only authorized request pass here
```
