### ISSUE TITLE
Proxy with mirrorPool panics under high QPS

### ISSUE THREAD

**Issue by samutamm** [megaease/easegress#407]
**Describe the bug**

I created HTTPPipeline with Proxy filter that has `mirrorPool` pointing to an [echo server](example/backend-service/echo/echo.go) and `mainPool` pointing to another echo server. I can query HTTPServer with `curl` without any problem, but if I send many queries in parallel with [ab](https://httpd.apache.org/docs/2.4/programs/ab.html) tool, there is an `panic: close of closed channel` error after few seconds.

**To Reproduce**
1. Start Easegress server `bin/easegress-server -f eg-server.yaml`.
2. Add  HTTPServer with `egctl object create -f httpserver.yaml`
3. Add HTTPPipeline with `egctl object create -f mirrorpool-pipeline.yaml`
4. Start [echo server](example/backend-service/echo/echo.go) at HOST2 and HOST3.
5. Send queries in parallel using `ab`:
```bash
ab -k -c 450 -n 1000000 -H "X-Mirror: mirror"  http://{HOST1}:10080/pipeline
```
After few second Easegress server fails with `panic: close of closed channel`.

**Expected behavior**

**Version**
1.4.0

**Configuration**
* Easegress Configuration
```yaml
# eg-server.yaml
name: machine-1
cluster-name: cluster-stress-test
cluster-role: primary
api-addr: localhost:2381
data-dir: ./data
wal-dir: ""
cpu-profile-file: "./cpu-profile.txt"
memory-profile-file: "./memory-profile.txt"
disable-access-log: true
log-dir: ./log
debug: false
cluster:
  listen-peer-urls:
   - http://{HOST1}:2380
  listen-client-urls:
   - http://{HOST1}:2379
  advertise-client-urls:
   - http://{HOST1}:2379
  initial-advertise-peer-urls:
   - http://{HOST1}:2380
  initial-cluster:
   - machine-1: http://{HOST1}:2380
```

* HTTP server configuration
```yaml
# httpserver.yaml
kind: HTTPServer
name: stress-server
port: 10080
keepAlive: true
https: false
maxConnections: 10240
rules:
  - paths:
    - pathPrefix: /pipeline
      backend: mirrorpool-pipeline
```

* Pipeline Configuration
```yaml
name: mirrorpool-pipeline
kind: HTTPPipeline
flow:
  - filter: proxy
filters:
  - kind: Proxy
    name: proxy
    mainPool:
      loadBalance:
        policy: roundRobin
      servers:
      - url: http://{HOST2}:9095
    mirrorPool:
      filter:
        headers:
          "X-Mirror":
            exact: mirror
      loadBalance:
        policy: roundRobin
      servers:
      - url: http://{HOST3}:9095
```

**Logs**
```
panic: close of closed channel

goroutine 4160 [running]:
github.com/megaease/easegress/pkg/filter/proxy.(*masterReader).Read(0xc005800390, {0xc00582a000, 0x8000, 0x8000})
	github.com/megaease/easegress/pkg/filter/proxy/masterslavereader.go:69 +0x17d
github.com/megaease/easegress/pkg/util/callbackreader.(*CallbackReader).Read(0xc005806b90, {0xc00582a000, 0xc00007c070, 0xc005449000})
	github.com/megaease/easegress/pkg/util/callbackreader/callbackreader.go:57 +0xa5
net/http.(*readTrackingBody).Read(0x0, {0xc00582a000, 0xc002afdb00, 0x44ced2})
	net/http/transport.go:634 +0x2a
io.(*multiReader).Read(0xc0056cba28, {0xc00582a000, 0x8000, 0x8000})
	io/multi.go:26 +0x9b
io.copyBuffer({0x7f3e41f08db0, 0xc0048b1890}, {0x2e430c0, 0xc0056cba28}, {0x0, 0x0, 0x0})
	io/io.go:423 +0x1b2
io.Copy(...)
	io/io.go:382
net/http.(*transferWriter).doBodyCopy(0xc0058041e0, {0x7f3e41f08db0, 0xc0048b1890}, {0x2e430c0, 0xc0056cba28})
	net/http/transfer.go:410 +0x4d
net/http.(*transferWriter).writeBody(0xc0058041e0, {0x2e3d5e0, 0xc002797080})
	net/http/transfer.go:357 +0x225
net/http.(*Request).write(0xc00577ac00, {0x2e3d5e0, 0xc002797080}, 0x0, 0xc005775d70, 0x0)
	net/http/request.go:698 +0xb4e
net/http.(*persistConn).writeLoop(0xc00153ad80)
	net/http/transport.go:2389 +0x189
created by net/http.(*Transport).dialConn
	net/http/transport.go:1748 +0x1e65
```

**OS and Hardware**
 - OS: Ubuntu 20.04
 - CPU:  Intel(R) Xeon(R)
 - Memory:  15GB
 - Host 1,2 and 3 are equivalent.
