### ISSUE TITLE
配置http代理完成后，不能访问代理的内容

### ISSUE THREAD

**Issue by martinou** [megaease/easegress#435]
**Describe the bug**
正常启动easegress，配置完成httpserver、httppipeline后，启动无异常。

但是不能通过http://10.10.*.*:10080 访问代理内容。

**To Reproduce**
1. Execute ' easegress-server --ip-addr xxx.xxx.12.3'
2. Send a request to 'postman http get'
3. no response

**Expected behavior**

**Version**
 1.4.1

**Configuration**
* Easegress Configuration
default
* HTTP server configuration
```
autoCert: false
caCertBase64: ""
cacheSize: 0
certBase64: ""
certs: {}
http3: false
https: false
keepAlive: true
keepAliveTimeout: 60s
keyBase64: ""
keys: {}
kind: HTTPServer
maxConnections: 10240
name: server-demo
port: 10080
rules:
- host: ""
  hostRegexp: ""
  paths:
  - backend: pipeline-demo
    headers: []
    pathPrefix: /pipeline
    rewriteTarget: ""
tracing: null
xForwardedFor: false
```

* Pipeline Configuration
```
filters:
- kind: Proxy
  mainPool:
    loadBalance:
      policy: roundRobin
    servers:
    - url: http://www.baidu.com
    - url: http://www.baidu.com
    - url: http://www.baidu.com
  name: proxy
flow:
- filter: proxy
  jumpIf: {}
kind: HTTPPipeline
name: pipeline-demo
```

**Logs**
```
Easegress logs, if applicable.
```

**OS and Hardware**
 - OS: centos 7.x
 - CPU: Intel(R) Core(TM) i5-8265U
 - Memory: 32GB

**Additional context**
