### ISSUE TITLE
Too many "http: TLS handshake error" log

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#481]
**Describe the bug**
When I deploy easegress as a single pod in aliyun k8s cluster and use LoadBalancer service，the pod print hugely too many TLS handshake error log in pod stdout console every one second or less than one second
Give one real log example as follow:
```log
2022/01/26 02:05:00 http: TLS handshake error from 100.97.231.2:49030: read tcp 172.26.5.88:443->100.97.231.2:49030: read: connection reset by peer
```
The easegress HTTPServer object yaml config as follow:(leave out tls cert and key for security)
```yaml
kind: HTTPServer
name: https
port: 443
keepAlive: true
https: true
globalFilter: globalFilter
certBase64: 
keyBase64: 
rules:
  - paths:
      - pathPrefix: /api
        backend: api-svc
```
The k8s service yaml config as follow:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: easegress
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: easegress
  sessionAffinity: None
  type: LoadBalancer
```
