### ISSUE TITLE
Http 302 redirect doesn't work in Easegress filter

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#485]
**Describe the bug**

I am developing custom filter for our SSO login and find I cannot do a 302 redirect in Easegress filter trying many ways.

As following code snippet shows:
```go
func (f *SSOFilter) Handle(ctx context.HTTPContext) (result string) {
	ctx.Response().SetStatusCode(302)
	ctx.Response().Header().Set("Location", "https://www.google.com")
	return "ssoFiltered"
}
```
Easegress obect config:
```yaml
kind: GlobalFilter
name: globalSSOFilter
beforePipeline:
  flow:
    - filter: SSOFilter
      jumpIf: { ssoFiltered: END }
  filters:
    - name: globalSSOFilter
      kind: SSOFilter
```
After accessing from Chrome web broswer.  Although the response header Location value does exist,
the return http status code is always 200, not 302 as expected.
