### ISSUE TITLE
Should update the kubernetes ingress status or address when acting as a ingress controller

### ISSUE THREAD

**Issue by codering** [megaease/easegress#506]
easegress does not set the ingress status of the fulfilled ingress, or address.

```yaml
kubectl get ing  hello-world-test -o yaml | grep status -A 3
status:
  loadBalancer: {}
```
For more information reference： https://github.com/traefik/traefik/issues/3377
