### ISSUE TITLE
The return value of method context.HTTPRequest.Path() is different from context.HTTPRequest.Std().URL.Path in url rewrite scenario

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#523]
**Describe the bug**
I am developing custom filter， in some case we need to ignore some request url by url path，But when I get url path from 
Easegress api  ```context.HTTPRequest.Path()```, the path is rewritten，if I use golang standard api  ```context.HTTPRequest.Std().URL.Path```, the path is not rewritten. I think this should be a Easegress HTTPRequest api implementation bug. Reproduce this case using following config:
```yaml
kind: HTTPServer
name: http
port: 80
keepAlive: true
https: false
rules:
  - paths:
      - pathRegexp: ^/static/(.*)$
        rewriteTarget: /$1
        backend: static-backend
---

name: static-backend
kind: HTTPPipeline
flow:
  - filter: dummy-filter
    jumpIf: { dummyFiltered: END }
  - filter: proxy
filters:
  - name: dummy-filter
    kind: DummyFilter
  - name: proxy
    kind: Proxy
    mainPool:
      servers:
        - url: http://127.0.0.1
      loadBalance:
        policy: roundRobin
```
DummyFilter code snippet just output and return:
```go
func (f *DummyFilter) Handle(ctx context.HTTPContext) (result string) {
	logger.Infof("ctx.Request().Path(): %s", ctx.Request().Path())
	logger.Infof("ctx.Request().Std().URL.Path: %s", ctx.Request().Std().URL.Path)
	return ctx.CallNextHandler("dummyFiltered")
}
```
Client request using curl:
```shell
curl http://127.0.0.1/static/a/b/c
```
The log output will be:
```log
...... ctx.Request().Path(): /a/b/c
...... ctx.Request().Std().URL.Path: /static/a/b/c
```
