### ISSUE TITLE
FaaSController does not set request Host as expected

### ISSUE THREAD

**Issue by samutamm** [megaease/easegress#554]
**Describe the bug**
FaaSController with knative provider uses `Host` and knative's [Temporary DNS](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#configure-dns) mechanism to tell Knative, which function to invoke. [FaaSController](https://github.com/megaease/easegress/blob/main/doc/cookbook/faas.md#examples) can be invoked curl command like this:

`curl http://127.0.0.1:${faas_controller_port}/${function_path} -H "X-FaaS-Func-Name: ${function_name}" -X POST
` which FaaSController routes to Knative, with following `Host`

`"Host: ${function_name}.${namespace}.${hostSuffix}"`

However, maybe after this change https://github.com/megaease/easegress/issues/447, RequestAdaptor cannot change the host properly and FaaSController + Knative don't invoke the function.

**To Reproduce**
1. Follow https://github.com/megaease/easegress/blob/main/doc/cookbook/faas.md to set up FaaSController and Knative backend. 
2. Execute `curl http://127.0.0.1:${faas_controller_port}/${function_path} -H "X-FaaS-Func-Name: ${function_name}" -X POST`
3. See 404 instead of the output of the function.

**Expected behavior**
Function invocation should work.
At least two options:
- Host is set properly without conflicting with https://github.com/megaease/easegress/issues/447 
- FaaSController knative provider could leverage Magic DNS or Real DNS instead of Temporary DNS (https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#configure-dns), eliminating the need to change the request host.

**Version**
The version number of Easegress.

**Configuration**
* Easegress Configuration
```yaml
name: faascontroller
kind: FaaSController           
provider: knative

syncInterval: 10s              

httpServer:
    http3: false               
    port: 10083                
    keepAlive: true            
    keepAliveTimeout: 60s      
    https: false
    certBase64:
    keyBase64:
    maxConnections: 10240      

knative:
   networkLayerURL: http://external-ip-of-kourier-gateway.cloud-provider.com
   hostSuffix: example.com
```
And function.yaml
```yaml
name:           "kn-eks-demo"                                                                                                                                   
image:          "gcr.io/knative-samples/helloworld-go"
port:           8080
autoScaleType:  "rps"          
autoScaleValue: "111"          
minReplica:     0
maxReplica:     3
limitCPU:       "1000m"         
limitMemory:    "2000Mi"        
requestCPU:     "80m"          
requestMemory:  "20Mi"         
requestAdaptor:                       
  header:
    set:
      X-Func: kn-eks-demo 
```

* HTTP server configuration
```yaml
```

* Pipeline Configuration
```yaml
```

**Logs**
```
Easegress logs, if applicable.
```

**OS and Hardware**
 - OS: [e.g. Ubuntu 20.04]
 - CPU:[e.g. Intel(R) Core(TM) i5-8265U]
 - Memory: [e.g. 16GB]

**Additional context**

---
Thanks for contributing 🎉!
