### ISSUE TITLE
Easegress server default start command configuration parameters are not overridden

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#556]
**Describe the bug**
Currently Easegress has two style cluster connection configuration in ```pkg/option/option.go:115```，if using one as input configuration,the other default will not be overridden，this lead to client cmd ```egctl member list``` return error result

**To Reproduce**
Start Easegress server using existing example directory scripts
```shell
./example/primary-001/start.sh
./example/primary-002/start.sh
```
After started, execute following command
```shell
./example/primary-001/egctl.sh member list
```
The return result(for clarity, just omit some snippets):
```yaml
- options:
    name: primary-001
    ......
    cluster-listen-client-urls:
    - http://localhost:2379
    cluster-listen-peer-urls:
    - http://localhost:2380
    cluster-advertise-client-urls:
    - http://localhost:2379
    cluster-initial-advertise-peer-urls:
    - http://localhost:2380
    cluster:
      listen-peer-urls:
      - http://127.0.0.1:12380
      listen-client-urls:
      - http://127.0.0.1:12379
      advertise-client-urls:
      - http://127.0.0.1:12379
      initial-advertise-peer-urls:
      - http://127.0.0.1:12380
      initial-cluster:
        primary-001: http://127.0.0.1:12380
        primary-002: http://127.0.0.1:22380
        primary-003: http://127.0.0.1:32380
   ......
    
- options:
    name: primary-002
    ......
    cluster-listen-client-urls:
    - http://localhost:2379
    cluster-listen-peer-urls:
    - http://localhost:2380
    cluster-advertise-client-urls:
    - http://localhost:2379
    cluster-initial-advertise-peer-urls:
    - http://localhost:2380
    cluster-join-urls: []
    cluster:
      listen-peer-urls:
      - http://127.0.0.1:22380
      listen-client-urls:
      - http://127.0.0.1:22379
      advertise-client-urls:
      - http://127.0.0.1:22379
      initial-advertise-peer-urls:
      - http://127.0.0.1:22380
      initial-cluster:
        primary-001: http://127.0.0.1:12380
        primary-002: http://127.0.0.1:22380
        primary-003: http://127.0.0.1:32380
      ......
```

**Expected behavior**

```yaml
- options:
    name: primary-001
    ......
    cluster-listen-client-urls:
    - http://localhost:12379
    cluster-listen-peer-urls:
    - http://localhost:12380
    cluster-advertise-client-urls:
    - http://localhost:12379
    cluster-initial-advertise-peer-urls:
    - http://localhost:12380
    cluster:
      listen-peer-urls:
      - http://127.0.0.1:12380
      listen-client-urls:
      - http://127.0.0.1:12379
      advertise-client-urls:
      - http://127.0.0.1:12379
      initial-advertise-peer-urls:
      - http://127.0.0.1:12380
      initial-cluster:
        primary-001: http://127.0.0.1:12380
        primary-002: http://127.0.0.1:22380
        primary-003: http://127.0.0.1:32380
   ......
    
- options:
    name: primary-002
    ......
    cluster-listen-client-urls:
    - http://localhost:22379
    cluster-listen-peer-urls:
    - http://localhost:22380
    cluster-advertise-client-urls:
    - http://localhost:22379
    cluster-initial-advertise-peer-urls:
    - http://localhost:22380
    cluster-join-urls: []
    cluster:
      listen-peer-urls:
      - http://127.0.0.1:22380
      listen-client-urls:
      - http://127.0.0.1:22379
      advertise-client-urls:
      - http://127.0.0.1:22379
      initial-advertise-peer-urls:
      - http://127.0.0.1:22380
      initial-cluster:
        primary-001: http://127.0.0.1:12380
        primary-002: http://127.0.0.1:22380
        primary-003: http://127.0.0.1:32380
      ......
```
