### ISSUE TITLE
HTTPPipeline creation failed (yaml tool version reason)

### ISSUE THREAD

**Issue by aniaan** [megaease/easegress#568]
**Is your feature request related to a problem? Please describe.**

Reproducible case

p.yaml

```
kind: HTTPPipeline
name: dev-tianji-activity-4-1648783865882
flow:
- filter: y
filters:
- name: y
  kind: Proxy
  mainPool:
    servers:
    - url: http://tianji-activity-service-dev-svc.tianji:8080
    loadBalance:
      policy: random
```

```shell
egctl object create -f p.yaml
```
**error**
```shell
Error: 400: generalErrs:
- '*httppipeline.Spec: flow: filter y not found'
- 'httppipeline.Spec: flow: filter y not found'
```

**reason**:

https://github.com/megaease/easegress/blob/0dc0d5acccaadc545f913aee58ea148c5dcf1f59/pkg/object/httppipeline/httppipeline.go#L70-L73

The type of Filters is map[string]interface. When the yaml tool is in Unmarshal, it will convert `y` to bool, causing the verification to fail.

https://github.com/go-yaml/yaml/issues/740
https://github.com/kubernetes/kubernetes/issues/102308

Other communities have also encountered type problems, which are probably the two solutions. 

1. Upgrade the yaml tool to the V3 version. 
2. Remind users that `y`, `n`, `yes`, `no` values cannot be used in some places

---
Thanks for contributing 🎉!
