### ISSUE TITLE
IngressController can not handle Ingress rule priority correctly

### ISSUE THREAD

**Issue by localvar** [megaease/easegress#633]
**Describe the bug**
IngressController can not handle Ingress rule priority correctly

**To Reproduce**
create two Ingress in k8s like:
```yaml
...
  rules:
  - http:
      paths:
      - backend:
          service:
            name: service1
        path: /v1
        pathType: Prefix
```
and
```yaml
...
  rules:
  - host: www.megaease.com
    http:
      paths:
      - backend:
          service:
            name: service2
        path: /v1
        pathType: Prefix
```
request to URL `http://www.megaease.com/v1/hello` is forwarded to service1.

**Expected behavior**
the request is forwarded to service2

**Version**
v1.5.2
