### ISSUE TITLE
MQTTProxy created failed after upgrade v2.0.0

### ISSUE THREAD

**Issue by codering** [megaease/easegress#693]
**Error message**

```
ERROR   rawconfigtrafficcontroller/rawconfigtrafficcontroller.go:165    BUG: unexpected kind string
```

**Version**
v2.0.0

**Configuration**
* MQTTProxy Configuration
```yaml
kind: MQTTProxy
name: mqttproxy
port: 1883
rules:
- when:
    packetType: Connect
  pipeline: pipeline-mqtt-auth
- when:
    packetType: Publish
  pipeline: pipeline-mqtt-publish
```

**Logs**
```
easegress  | 2022-07-08T12:47:21.17+08:00       INFO    server/main.go:61       Easegress release: v2.0.0, repo: megaease/easegress, commit: 279db8c99063173aa63b72b9983dabe97dd84440
easegress  | 2022-07-08T12:47:21.17+08:00       INFO    cluster/config.go:106   etcd config: advertise-client-urls: [{Scheme:http Opaque: User: Host:localhost:2379 Path: RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}] advertise-peer-urls: [{Scheme:http Opaque: User: Host:localhost:2380 Path: RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}] init-cluster: eg-default-name=http://localhost:2380 cluster-state: new force-new-cluster: false
easegress  | 2022-07-08T12:47:21.985+08:00      INFO    cluster/cluster.go:332  client connect with endpoints: [http://localhost:2380]
easegress  | 2022-07-08T12:47:21.987+08:00      INFO    cluster/cluster.go:346  client is ready
easegress  | 2022-07-08T12:47:22.005+08:00      INFO    cluster/cluster.go:638  server is ready
easegress  | 2022-07-08T12:47:22.046+08:00      INFO    cluster/cluster.go:498  lease is ready (grant new one: b6a81dc22417007)
easegress  | 2022-07-08T12:47:22.047+08:00      INFO    cluster/cluster.go:218  cluster is ready
easegress  | 2022-07-08T12:47:22.143+08:00      INFO    supervisor/supervisor.go:137    create TrafficController
easegress  | 2022-07-08T12:47:22.143+08:00      INFO    supervisor/supervisor.go:137    create RawConfigTrafficController
easegress  | 2022-07-08T12:47:22.144+08:00      INFO    supervisor/supervisor.go:137    create ServiceRegistry
easegress  | 2022-07-08T12:47:22.144+08:00      INFO    supervisor/supervisor.go:137    create StatusSyncController
easegress  | 2022-07-08T12:47:22.144+08:00      INFO    statussynccontroller/statussynccontroller.go:139        StatusUpdateMaxBatchSize is 20
easegress  | 2022-07-08T12:47:22.144+08:00      INFO    cluster/cluster.go:538  session is ready
easegress  | 2022-07-08T12:47:22.144+08:00      INFO    api/api.go:73   register api group admin
easegress  | 2022-07-08T12:47:22.145+08:00      INFO    api/server.go:86        api server running in 0.0.0.0:2381
easegress  | 2022-07-08T12:47:22.165+08:00      ERROR   rawconfigtrafficcontroller/rawconfigtrafficcontroller.go:165    BUG: unexpected kind string
```

**OS and Hardware**
 - OS: MacOS 12
 - CPU: Intel
 - Memory:  16G

**Additional context**
```yaml
## docker-compose.yaml
services:
  easegress:
    image: megaease/easegress:v2.0.0
    container_name: easegress
    ports:
      - "2380:2380"
      - "2381:2381"
      - "1883:1883"
    environment:
      - TZ=Asia/Shanghai
    command: >
      sh -c "easegress-server 
      --api-addr 0.0.0.0:2381
      --initial-object-config-files /opt/easegress/myconfig/mqttproxy.yaml"
    volumes: 
      - $W/easegress/config:/opt/easegress/myconfig

```
