### ISSUE TITLE
The WASM code cannot run on MacOS system

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#700]
**Describe the bug**
On MacOS system running WebAssembly code in Easegress report following error whether using [easegress-assemblyscript-sdk](https://github.com/megaease/easegress-assemblyscript-sdk) or [easegress-go-sdk](https://github.com/xmh19936688/easegress-go-sdk)
```log
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/c-api/src/linker.rs:105:80
2022-07-12T10:23:37.039+08:00   ERROR   wasmhost/wasmhost.go:331        recovered from wasm error: runtime error: invalid memory address or nil pointer dereference
2022-07-12T10:23:37.039+08:00   ERROR   httpserver/mux.go:437   http-server: response is nil
```

**To Reproduce**
Just following README.md doc instruction

**OS Version**
Darwin 20.4.0 x86_64

**Comment by jthann** [comment]
@suchen-sci   This error log line ```ERROR   httpserver/mux.go:437   http-server: response is nil``` can be easily reproduced：using Easegress v2.0.0  don't configure proxy filter，just handle logic and return response in Wasm code.
The bug may be caused by that the response object is nil and not created by default in wasm code, like [this issue](https://github.com/megaease/easegress/issues/702)

**Comment by localvar** [comment]
@jthann , the behavior has been changed because v2.0 does not have a default response. We can now use a ResponseBuilder before the WasmHost to create the response as a workaround. We will enhance the WasmHost filter to make it able to access requests/responses in any namespace later.

**Comment by jthann** [comment]
It work out okay after adding ResponseBuilder filter
```
name: wasm-demo-pipeline
kind: Pipeline
flow:
- filter: respBuilder
- filter: wasm
filters:
- name: respBuilder
  kind: ResponseBuilder
  template: |
    statusCode: 200
- name: wasm
  kind: WasmHost
  code: wasm-demo.wasm
```
