### ISSUE TITLE
Upgrade Easegress from 1.x.x to 2.0.0，fetch Response Object from context.Context is nil 

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#702]
**Describe the bug**
After upgrading Easegress custom filter from v1.x to 2.0.0 following [doc instruction] (https://github.com/megaease/easegress/blob/main/doc/cookbook/migrate-v1-filter-to-v2.md). When change ```ctx.Response()``` in  to ```ctx.GetInpuputResponse().(*httpprot.Response)``` or  ```ctx.GetOutputResponse().(*httpprot.Response)```，the ctx.GetInpuputResponse() and ctx.GetOutputResponse() return result is nil and filter report error.

**To Reproduce**
using v2.0.0 Easegress and using following config and code to reproduce:
Configuration:
```yaml
kind: HTTPServer
name: http
port: 8080
keepAlive: true
https: false
globalFilter: globalFilter
rules:
  - paths:
      - pathPrefix: /pipeline
        backend: echo-backend
---
kind: GlobalFilter
name: globalFilter
beforePipeline:
  flow:
    - filter: auth-filter
  filters:
    - name: auth-filter
      kind: AuthFilter
---
name: echo-backend
kind: Pipeline
flow:
  - filter: proxy
filters:
  - name: proxy
    kind: Proxy
    pools:
      - loadBalance:
          policy: roundRobin
        servers:
          - url: http://127.0.0.1:9095
```
```go
func (a *AuthFilter) Handle(ctx *context.Context) string {
      // omit some code, here resp1 and resp2 are nil
      resp1 := ctx.GetInputResponse().(*httpprot.Response)
      resp2 := ctx.GetOutputResponse().(*httpprot.Response)
}
```
