### ISSUE TITLE
The jumpIf logic in GlobalFilter object beforePipeline flow  cannot work properly as that in Pipeline object flow

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#703]
**Describe the bug**
Right now we need GlobalFilter Object config to avoid configuring the custom filter in every pipeline object.  But the jumpIf logic in GlobalFilter object beforePipeline flow is not work properly as that in Pipeline object flow

**To Reproduce**
Using Easegress 2.0.0 and following Demo code and config，echo-backend service providing 9095 port is from [example](https://github.com/megaease/easegress/tree/main/example/backend-service/echo)

1、DemoAuthFilter code 
```go
const (
	Kind              = "DemoAuthFilter"
	ResultAuthInvalid = "authInvalid"
)

var kind = &filters.Kind{
	Name:        Kind,
	Description: "DemoAuthFilter",
	Results:     []string{ResultAuthInvalid},
	DefaultSpec: func() filters.Spec {
		return &Spec{}
	},
	CreateInstance: func(spec filters.Spec) filters.Filter {
		return &DemoAuthFilter{spec: spec.(*Spec)}
	},
}

func init() {
	filters.Register(kind)
}

type (
	DemoAuthFilter struct {
		spec *Spec
	}

	Spec struct {
		filters.BaseSpec `yaml:",inline"`
	}
)

func (d *DemoAuthFilter) Name() string {
	return d.spec.Name()
}

func (d *DemoAuthFilter) Kind() *filters.Kind {
	return kind
}

func (d *DemoAuthFilter) Spec() filters.Spec {
	return d.spec
}

func (d *DemoAuthFilter) Init() {
}

func (d *DemoAuthFilter) Inherit(previousGeneration filters.Filter) {
	d.Init()
}

func (d *DemoAuthFilter) Handle(ctx *context.Context) string {
	r := ctx.GetInputRequest().(*httpprot.Request)
	authHeader := r.HTTPHeader().Get("Authorization")
	if len(authHeader) == 0 {
		resp, _ := httpprot.NewResponse(nil)
		resp.SetStatusCode(http.StatusUnauthorized)
		resp.SetPayload("unauthorized")
		ctx.SetOutputResponse(resp)
		return ResultAuthInvalid
	}
	return ""
}
func (d *DemoAuthFilter) Status() interface{} {
	return nil
}

func (d *DemoAuthFilter) Close() {
}
```

2、Not Using GlobalFilter config
```yaml
kind: HTTPServer
name: http
port: 8080
keepAlive: true
https: false
rules:
  - paths:
      - pathPrefix: /pipeline
        backend: echo-backend
---
name: echo-backend
kind: Pipeline
flow:
  - filter: auth-filter
    jumpIf:
      authInvalid: END
  - filter: proxy
filters:
  - name: auth-filter
    kind: DemoAuthFilter
  - name: proxy
    kind: Proxy
    pools:
      - loadBalance:
          policy: roundRobin
        servers:
          - url: http://127.0.0.1:9095
```

3、Using GlobalFilter config
```yaml
kind: HTTPServer
name: http
port: 8080
https: false
globalFilter: globalFilter
rules:
  - paths:
      - pathPrefix: /pipeline
        backend: echo-backend
---
kind: GlobalFilter
name: globalFilter
beforePipeline:
  flow:
    - filter: auth-filter
      jumpIf:
        authInvalid: END
  filters:
    - name: auth-filter
      kind: DemoAuthFilter
---
name: echo-backend
kind: Pipeline
flow:
  - filter: proxy
filters:
  - name: proxy
    kind: Proxy
    pools:
      - loadBalance:
          policy: roundRobin
        servers:
          - url: http://127.0.0.1:9095
```

4、Using curl cmd to send request
```shell
curl 127.0.0.1:8080/pipeline -v
```
When not using GlobalFilter config，the http response code is  401 and body is "unauthorized" as expected，But when using GlobalFilter config, the http request is proxied to echo backend service.
