### ISSUE TITLE
It's impossible to get origin request url path in rewrite scenario

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#718]
**Describe the bug**
Using Easegress v2.0.0，in custom auth login filter，we need to ignore handling some requests by client request url path，but it is impossible to get origin client url path in rewrite scenario，the issue is opened in [issue 523](https://github.com/megaease/easegress/issues/523) related to Easegress v1.x  and still not resolved  in v2.0.0.

**Comment by localvar** [comment]
Hi @jthann , I think I need more information to understand the requirement.

My current understanding is that you should not use `rewrite` in the case, but use a `RequestAdaptor` after the custom filter to modify the path. And I checked the [Nginx documentation](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite), it hasn't say Nginx will keep the original path either.

**Comment by jthann** [comment]
@localvar Yes，perhaps using RequestAdaptor can solve the problem，but I think it's not an elegant way. By the way Nginx will keep the original path in ```request_uri``` variable and keep the rewrite path in ```uri``` variable，request_uri and uri is equal under no rewritten condition.  We can do a simple test  to verify this in nginx using following nginx.conf fragment and nginx listen on 80 port
```
location /first {
   rewrite /first(.*) /second$1;
   return 200 'request_uri: $request_uri; uri:$uri\n';
}
```
Use   ```curl 127.0.0.1/first/api``` to send request,  the response body will be ```request_uri: /first/api; uri:/second/api```

In our scene，we have 60+  backend services developed by different departments deploying in one k8s cluster, as following HTTPServer config fragment, some services use path prefix like service1 to route and some services use path regex like service2 to route. We have developed our own custom SSO filter to handle login state logic and in this filter we need to get origin request url path to do some validation logic that is not provided by RequestAdaptor.   In addition, if using RequestAdaptor，this means some backend pipeline use RequestAdaptor,  some backend pipeline not， the config is inconsistent and hard to maintain.
```yaml
kind: HTTPServer
name: https
port: 443
rules:
  - host: xxx
    paths:
      - pathPrefix: /svc1
         backend: service1
      - pathRegexp: ^/svc2/(.*)$
         rewriteTarget: /$1
         backend: service2
      //omit others 60+ service for clarity
---
name: service1
kind: Pipeline
flow:
  - filter: proxy
filters:
  - name: proxy
    kind: Proxy
    pools:
      - serviceRegistry: nacos
        serviceName: service1
        loadBalance:
          policy: roundRobin
//omit others 60+ Pipeline for clarity
```
So I prefer that Easegress should separate origin client request url path from url path rewritten in rewrite scenario just like nginx and provide api for both getting origin client request url path and rewrite url path. Currently just setting rewritten url path like ```r.Std().URL.Path = path``` is not a proper way.
