### ISSUE TITLE
Easegress Tracing should add yaml configuration item to disable reporting

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#735]
Currently，when configure Easegress Zipkin，it will report ```SpanModel``` data to dashboard backend， but in some cases for instance in local debug development or other environment without Zipkin dashboard. We just need Zipkin to generate TraceID and propagate to backend services for distributed logging.  If report is not disabled，there are a lot of error reporting logs as following every one second affecting normal logs
```failed to send the request: Post "http://localhost:9412/api/v2/spans": dial tcp 127.0.0.1:9412: connect: connection refused```
So Zipkin should add a yaml configuration item like ```enableReport``` (or other names)for user to decide not to report Zipkin  
span model.   Under this assumption，we can use [Zipkin noopReporter](https://github.com/openzipkin/zipkin-go/blob/f91647633b041da6b71741a09c8ff5d7c06364e2/reporter/reporter.go#L39).
Just like Spring Cloud Zipkin Configuration item:  [spring.zipkin.enabled](https://github.com/spring-cloud/spring-cloud-sleuth/blob/6ce9a43f462b1695ac78867eae652f61778a93cb/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/ZipkinProperties.java#L56)
```
kind: HTTPServer
name: http
port: 9080
https: false
tracing:
  serviceName: https
  zipkin:
    serverURL: http://localhost:9412/api/v2/spans
    enableReport: false
    sampleRate: 1
    sameSpan: true
```
