### ISSUE TITLE
[Bug]: GlobalFilter jsonschema validator always return 400 when afterPipeline not configured

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#797]
**Describe the bug**
When creating GlobalFilter object in Easegress using egctl，the response always return 400 code

**To Reproduce**
Using following yaml config,  the DummyFilter can be replaced by any reasonable filters
```yaml
kind: GlobalFilter
name: globalFilter
beforePipeline:
  flow:
    - filter: dummy-filter
  filters:
    - name: dummy-filter
      kind: DummyFilter
```
The response returned is 
```
Error: 400: {"jsonschemaErrs":["afterPipeline: Must validate one and only one schema (oneOf)","afterPipeline.filters: Invalid type. Expected: array, given: null"]}
```

**Expected behavior**
GlobalFilter jsonschema validator should return 200 ok when afterPipeline not configured
