### ISSUE TITLE
[Bug]: EaseMonitorMetrics Status error

### ISSUE THREAD

**Issue by wj-stack** [megaease/easegress#800]
**Describe the bug**
I need to send the monitoring data to Kafka, but I find that it is not sent successfully

```

- kafka:
    brokers:
        - 127.0.0.1:9092
    topic: metrics
  kind: EaseMonitorMetrics
  name: easemonitor-metrics-example
  version: easegress.megaease.com/v2

```

When I change the following code (statussynccontroller.go)

```
					su := newStatusUnit(namespace, trafficObject.Name,
						unixTimestamp, trafficObject.TrafficObjectStatus)

```
into

```
					su := newStatusUnit(namespace, trafficObject.Name,
						unixTimestamp, trafficObject.TrafficObjectStatus.Status) // change
```

The problem is solved

Hopefully it will be validated and submitted to new code

---
Thanks for contributing 🎉!
