### ISSUE TITLE
[Bug]: wasm apply data command not worked

### ISSUE THREAD

**Issue by grootpiano** [megaease/easegress#938]
**Describe the bug**
Hi guys, I found two kind of issues when walking through our [Flash Sale](https://github.com/megaease/easegress/blob/main/doc/cookbook/flash-sale.md) demo.

**Issue 1:** Parameters' type error in section 6.1 example spec

According to WasmHost filter's spec declaration, [parameters](https://github.com/megaease/easegress/blob/main/pkg/filters/wasmhost/wasmhost.go#L94)' value type should be `string`:

```go
type Spec struct {

    Parameters     map[string]string `json:"parameters" jsonschema:"omitempty"`

}
```

But the example in section [6.1 Parameters](https://github.com/megaease/easegress/blob/main/doc/cookbook/flash-sale.md#61-parameters) used a number value:
```yaml
filters:
  - name: wasm
    kind: WasmHost
    parameters:                                        # +
      startTime: "2021-08-08T00:00:00+00:00"           # +
      blockRatio: 0.4                                  # +
      maxPermission: 3                                 # +
```
So `egctl` client returned error:
```shell
Error: 400: {"generalErrs":["*pipeline.Spec: filters: json: cannot unmarshal number into Go struct field Spec.parameters of type string"]}
```
---

**Issue 2:** Wasm `apply-data` command not worked

When executing the command below, I got this error:
```shell
$ echo '
id/user4: "true"
id/user5: "true"' | egctl wasm apply-data flash-sale-pipeline wasm
Error: name is empty:
id/user4: "true"
id/user5: "true"
```

I found that we used [SpecVisitor](https://github.com/megaease/easegress/blob/main/cmd/client/command/wasm.go#L88) to get spec doc:
```go
Run: func(cmd *cobra.Command, args []string) {
    visitor := buildSpecVisitor(specFile, cmd)

}
```

But `SpecVisitor` [did not allow empty name](https://github.com/megaease/easegress/blob/main/cmd/client/command/visitor.go#L97):
```go
func (v *specVisitor) Visit(fn func(*spec) error) error {

	err := v.v.Visit(func(yamlDoc []byte) error {

		if s.Name == "" {
			return fmt.Errorf("name is empty: %s", doc)
		}

	})

}
```

And another issue I found in the same command is that we used [createObject](https://github.com/megaease/easegress/blob/main/pkg/api/object.go#L51) handler to hanle apply data request instead of [wasmApplyData](https://github.com/megaease/easegress/blob/main/pkg/api/wasm.go#L159) handler:
```go
Run: func(cmd *cobra.Command, args []string) {

    visitor.Visit(func(s *spec) error {
        handleRequest(http.MethodPost, makeURL(objectsURL), []byte(s.doc), cmd)

    })

}
```

**Version**
Latest main branch version.
