### ISSUE TITLE
[Bug]: The WebSocketProxy Filter does not work

### ISSUE THREAD

**Issue by qdongxu** [megaease/easegress#981]
**Describe the bug**

Using `curl` to send a request will get a successful response by following the [WebSocket Cookbook](https://github.com/megaease/easegress/blob/main/doc/cookbook/websocket.md) 

But after a real WebSocket server and client are deployed, the connection is not established.  The error in easegress's log:

> ERROR   httpproxy/wspool.go:183 websocketproxy#wsproxy#main: dial to ws://127.0.0.1:8765 failed: websocket.Dial ws://127.0.0.1:8765/ws: unsupported extensions

**To Reproduce**

1. WebSocket server:
```python
import asyncio
import websockets

async def hello(websocket, path):
    name = await websocket.recv()
    print(f"Greetings {name}!")

    greeting = f"Hello {name}!"
    await websocket.send(greeting)

start_server = websockets.serve(hello, "localhost", 8765)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```
2. Websocket Client:

```python
import asyncio
import websockets

async def hello():
    async with websockets.connect("ws://localhost:8765/ws") as websocket:
        name = "John"
        await websocket.send(name)
        greeting = await websocket.recv()
        print(f"{greeting}")

asyncio.get_event_loop().run_until_complete(hello())
```

the client was verified by sending to the server directly and through an Nginx reverse proxy.

4. config a Easegress http server:

```yml
kind: HTTPServer
name: http-8089-example
port: 8089
rules:
  - paths:
    - pathPrefix: /api/v1/tts
      backend: http-pipeline-tts
    - pathPrefix: /ws
      backend: websocket-pipeline
```
5. configure a Easegress websocket proxy:

```yaml
name: websocket-pipeline
kind: Pipeline

flow:
- filter: wsproxy

filters:
- kind: WebSocketProxy
  name: wsproxy
  defaultOrigin: http://127.0.0.1:8089/ws
  pools:
  - servers:
    - url: ws://127.0.0.1:8765
```
6. update the URL to `ws://localhost:8089/ws' in c.py.
7. execute c.py and it failed. 
 
**Expected behavior**

expected c.py output 'Hello John!'   when the Easegress is used as a WebSocket proxy.

**Version**
The version number of Easegress.
v2.4.0

**Configuration**
* Easegress Configuration
```yaml
```

* HTTP server configuration
```yaml
```

* Pipeline Configuration
```yaml
```

**Logs**
```
Easegress logs, if applicable.
```

**OS and Hardware**
 - OS: [e.g. Ubuntu 20.04]
 - CPU:[e.g. Intel(R) Core(TM) i5-8265U]
 - Memory: [e.g. 16GB]

**Additional context**

---
Thanks for contributing 🎉!
