### ISSUE TITLE
[feature] WebSocket support

### ISSUE THREAD

**Issue by benja-wu** [megaease/easegress#99]
## Background
* Easegress is popular for reverse proxy usage in production and development scenarios.
* In reversed proxy use cases, `WebSocket` is a widely used protocol for a full-duplex communication solution between client and server. It relies on TCP.[1] 
* Many reverse proxy support `WebSocket`,e.g., NGINX[2], Traefik, and so on.

## Proposal 
* Bring `WebSocketServer` as an BusinessController to Easegress. (Should treat it as an `HTTPServer` like traffic gate in the future. )
* Using `github.com/gorilla/websocket` as the `WebSocket` client implementation, since it has rich features supproted and a quite active community.（15k star/2.5k fork) Comparing to the original `golang.org/x/net/websocket` package, it can `receive fragmented message` and `send close message`.[3]

## Design
1. Spec 
```yaml
kind: WebSocketServer
name: websocketSvr
https: false                  # client need to use http/https firstly for connection upgrade      
certBase64:
keyBase64:
port: 10020                   # proxy servers listening port

backend: ws://localhost:3001  # the reserved proxy target
                              #  Easegress will exame the backend URL's scheme, If it starts with `wss`,
                              #  then `wssCerBase64` and `wssKeyBase64` must not be empty

wssCertBase64:                # wss backend certificate in base64 format
wssKeyBase64:                 # wss backend key in base64 format
```
2. Request sequence
```
   +--------------+                +--------------+                +--------------+  
   |              |  1             |              |   2            |              | 
   |   client     +--------------->|  Easegress   +--------------->|  websocket   |
   |              |<---------------+(WebSocketSvr)|<---------------+  backend     | 
   |              |  4             |              |   3            |              |
   +--------------+                +--------------+                +--------------+
```
3. The `WebSocketServer` shares some configurations with `HTTPServer`. Since `WebSocket` runs on `HTTP 1.1` only, and it works on opening two long-life goroutines for the reverse proxy scenario, it's quite different from the original Easegress' HTTPServer+Pipeline's process. So I decide not to implement it into `HTTPServer` and catalog it into `TrafficGate` in the first version right now. 

4. I will implement this `WebSocketServer` first version and try to figure out how to integrate with the original `HTTPServer` at the same time. (Moreover, multiple protocols supporting requirements, such as `MQTT`, `TPC`, are on the way... )

## References
1. https://datatracker.ietf.org/doc/html/rfc6455
2. https://www.nginx.com/blog/websocket-nginx/
3. https://github.com/gorilla/websocket
